---
# tasks file for resolv_conf

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - resolv_conf

- name: Create /etc/resolv.conf configuration
  become: yes
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - resolv_conf

- include: RedHat.yml
  when: ansible_distribution == "RedHat"
